version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- "
    target-branch: main
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- "
    target-branch: main
    open-pull-requests-limit: 0

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (github actions) "
    target-branch: main
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: "/environment/prod/app"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (docker dev) "
    target-branch: main
    open-pull-requests-limit: 0
