version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
      time: "06:30"
    commit-message:
      prefix: "#5 - (php) "
    target-branch: main
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "06:30"
    commit-message:
      prefix: "#5 - (js) "
    target-branch: main
    open-pull-requests-limit: 1
