#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Input\ArgvInput;

define("LARAVEL_START", microtime(true));

require __DIR__ . "/vendor/autoload.php";

$application = (require_once __DIR__ . "/bootstrap/app.php");
$status = $application->handleCommand(new ArgvInput());

exit($status);
