#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

define("LARAVEL_START", microtime(true));

require __DIR__ . "/vendor/autoload.php";

$app = require_once __DIR__ . "/bootstrap/app.php";
/** @var Kernel $kernel */
$kernel = $app->make(Kernel::class);

$input = new ArgvInput();
$status = $kernel->handle($input, new ConsoleOutput());

$kernel->terminate($input, $status);

exit($status);
