#!/bin/bash

if [ ! -f ".env" ]; then
   cp .env.example .env
fi

docker-compose build --no-cache --pull
docker-compose up -d
docker-compose run --rm -u "$(id -u):$(id -g)" php composer install
docker-compose run --rm -u "$(id -u):$(id -g)" php php artisan key:generate
docker-compose run --rm -u "$(id -u):$(id -g)" php php artisan migrate --seed
docker-compose run --rm -u "$(id -u):$(id -g)" node npm install
docker-compose run --rm -u "$(id -u):$(id -g)" node npm run dev
