name: Test & lint PHP stuff

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - '.env.ci'
      - 'test-and-lint-php.yml'

permissions:
  contents: read

jobs:
  test-and-lint-php:
    name: Test & lint PHP stuff
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=docker depName=php
      PHP_VERSION: 8.4.22
    services:
      postgres:
        image: postgres:15@sha256:3b0d656f5fff31c7d8a64f500a703dcf3f35e98ce78f602831a73059a5e6a012
        env:
          POSTGRES_DB: toby-test
          POSTGRES_USER: toby
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: vendor
          key: ${{ runner.os }}-composer-dependencies-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-dependencies

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, intl, gd
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Run PHP linter
        run: composer cs

      - name: Execute tests
        run: |
          cp .env.ci .env
          php artisan test --colors=always
