name: Test & lint JS stuff

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**.js'
      - '**.vue'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  test-and-lint-js:
    name: Test & lint JS stuff
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package.lock') }}
          restore-keys: ${{ runner.os }}-npm-dependencies

      - name: Set up node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.22.2

      - name: Instal npm dependencies
        run: npm clean-install

      - name: Run JS linter
        run: npm run lint
